# Generated by Django 5.1.6 on 2025-03-14 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0011_remove_quotationline_quotation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pkg_name', models.CharField(max_length=200)),
                ('pkg_description', models.TextField()),
                ('images', models.ImageField(blank=True, null=True, upload_to='package_images/')),
                ('pkg_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_archived', models.BooleanField(default=False)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.vendor')),
            ],
        ),
    ]
