# Generated by Django 5.1.6 on 2025-03-13 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_unavailabledate_customuser_google_authorized'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('contact_no', models.CharField(max_length=15)),
                ('event_name', models.CharField(max_length=255)),
                ('event_date', models.DateField()),
                ('event_state', models.CharField(choices=[('booked', 'Booked'), ('on_hold', 'On Hold')], default='on_hold', max_length=10)),
                ('google_event_id', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.vendor')),
            ],
        ),
    ]
