# Generated by Django 5.1.6 on 2025-03-13 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_vendorevent_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorevent',
            name='vendor_package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.vendorpackage'),
        ),
    ]
