# Generated by Django 5.1.6 on 2025-03-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_vendorevent_vendor_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorevent',
            name='contact_no',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
