# Generated by Django 5.1.6 on 2025-03-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_quotation_quotationline'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='payment_method',
            field=models.TextField(default='Test'),
            preserve_default=False,
        ),
    ]
