# Generated by Django 5.1.6 on 2025-03-14 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_quotation_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='confirmed_date',
            field=models.DateField(null=True, blank=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotation',
            name='customer_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='customer_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotation',
            name='receipt_attachment',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('accepted', 'Accepted'), ('in_payment', 'In Payment'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=15),
        ),
    ]
