# Generated by Django 5.1.6 on 2025-03-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_quotation_confirmed_date_quotation_customer_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='confirmed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
