# Generated by Django 5.1.6 on 2025-03-14 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_quotation_confirmed_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationline',
            name='quotation',
        ),
        migrations.RemoveField(
            model_name='vendorevent',
            name='customer_user',
        ),
        migrations.RemoveField(
            model_name='vendorevent',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='vendorevent',
            name='vendor_package',
        ),
        migrations.RemoveField(
            model_name='vendorpackage',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='Quotation',
        ),
        migrations.DeleteModel(
            name='QuotationLine',
        ),
        migrations.DeleteModel(
            name='VendorEvent',
        ),
        migrations.DeleteModel(
            name='VendorPackage',
        ),
    ]
